# Generated by Django 2.0.7 on 2018-07-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
