# Generated by Django 2.0.5 on 2018-07-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='FormContact',
        ),
    ]
