# Generated by Django 2.0.5 on 2018-07-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20180710_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickContact',
        ),
    ]
