# Generated by Django 2.0.5 on 2018-07-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='description',
        ),
    ]
