# Generated by Django 2.0.5 on 2018-07-16 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_quote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='timestrimp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
