# Generated by Django 2.0.5 on 2018-07-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20180716_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='timestrimp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
