# Generated by Django 2.0.5 on 2018-07-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20180722_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
