# Generated by Django 2.0.5 on 2018-07-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_remove_quote_timestrimp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
