# Generated by Django 2.0.5 on 2018-07-22 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20180722_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='timestrimp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
