# Generated by Django 2.0.7 on 2018-07-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180705_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
