# Generated by Django 2.0.7 on 2018-07-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180705_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
