# Generated by Django 2.0.5 on 2018-07-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180714_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='parent',
            new_name='comment',
        ),
    ]
