# Generated by Django 2.0.5 on 2018-07-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_blog_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childtag',
            name='parent_tag',
        ),
        migrations.DeleteModel(
            name='ParentTag',
        ),
    ]
