# Generated by Django 2.0.5 on 2018-07-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
