# Generated by Django 2.0.5 on 2018-07-08 12:43

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to=service.models.get_service_image_name)),
                ('title_2', models.CharField(blank=True, max_length=100)),
                ('details_2', models.TextField(blank=True)),
                ('image_2', models.ImageField(blank=True, upload_to=service.models.get_service_image_name)),
                ('showcase_image_1', models.ImageField(blank=True, upload_to=service.models.get_service_image_name)),
                ('showcase_image_2', models.ImageField(blank=True, upload_to=service.models.get_service_image_name)),
                ('showcase_image_3', models.ImageField(blank=True, upload_to=service.models.get_service_image_name)),
                ('title_3', models.CharField(blank=True, max_length=100)),
                ('details_3', models.TextField(blank=True)),
                ('title_4', models.CharField(blank=True, max_length=100)),
                ('details_4', models.TextField(blank=True)),
            ],
        ),
    ]
