# Generated by Django 2.0.5 on 2018-07-08 13:16

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20180708_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, upload_to=service.models.get_service_image_name),
        ),
    ]
