# Generated by Django 2.0.5 on 2018-07-09 07:19

from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('service', '0005_auto_20180708_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=service.models.get_category_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.Category'),
        ),
    ]
