# Generated by Django 2.0.5 on 2018-07-14 03:54

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=service.models.get_feature_image_name)),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField()),
            ],
        ),
    ]
