# Generated by Django 2.0.5 on 2018-07-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_pricetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTableFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pricetable',
            name='details',
            field=models.ManyToManyField(blank=True, to='service.PriceTableFeature'),
        ),
    ]
