# Generated by Django 2.0.5 on 2018-07-08 09:22

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=home.models.get_banner_image_name)),
            ],
        ),
    ]
