# Generated by Django 2.0.5 on 2018-07-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('pk',)},
        ),
    ]
