# Generated by Django 2.0.5 on 2018-07-12 08:53

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to=home.models.get_testimonial_image_name)),
                ('speach', models.TextField()),
            ],
        ),
    ]
