# Generated by Django 2.0.5 on 2018-07-10 15:54

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to=about.models.get_team_image_name),
        ),
    ]
