# Generated by Django 2.0.5 on 2018-07-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image_2',
        ),
    ]
