# Generated by Django 2.0.5 on 2018-07-13 10:11

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_aboutus_image_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=about.models.get_company_image_name)),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
        ),
    ]
