# Generated by Django 2.0.5 on 2018-07-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_generalinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='number',
            field=models.IntegerField(),
        ),
    ]
