# Generated by Django 2.0.5 on 2018-07-16 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20180716_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFromTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Team')),
            ],
        ),
    ]
