# Generated by Django 2.0.5 on 2018-07-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_messagefromteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
