# Generated by Django 2.0.5 on 2018-07-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_team_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=80)),
                ('sub_title', models.CharField(max_length=150)),
                ('details', models.TextField()),
            ],
        ),
    ]
