# Generated by Django 2.0.5 on 2018-07-16 06:49

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_whoweare'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='image',
            field=models.ImageField(upload_to=about.models.get_whoweare_image_name),
        ),
    ]
