# Generated by Django 2.0.5 on 2018-07-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20180716_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweare',
            name='strategy',
            field=models.ManyToManyField(to='about.CompanyStrategy'),
        ),
    ]
