# Generated by Django 2.0.5 on 2018-07-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_whoweare_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoweare',
            name='strategy',
            field=models.ManyToManyField(blank=True, to='about.CompanyStrategy'),
        ),
    ]
