# Generated by Django 2.0.5 on 2018-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_auto_20180716_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('strategy', models.ManyToManyField(blank=True, to='about.CompanyStrategy')),
            ],
        ),
    ]
