# Generated by Django 2.0.5 on 2018-07-16 11:37

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='logo',
            field=models.ImageField(blank=True, upload_to=about.models.get_logo_image_name),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='logo_2',
            field=models.ImageField(blank=True, upload_to=about.models.get_logo_image_name),
        ),
    ]
