# Generated by Django 2.0.5 on 2018-07-09 01:51

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0005_auto_20180708_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to=portfolio.models.get_portfolio_image_name)),
                ('image_2', models.ImageField(blank=True, upload_to=portfolio.models.get_portfolio_image_name)),
                ('image_3', models.ImageField(blank=True, upload_to=portfolio.models.get_portfolio_image_name)),
                ('details_2', models.TextField(blank=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Service')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
