# Generated by Django 2.0.5 on 2018-07-10 12:48

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(default=portfolio.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, related_query_name='portfolio_category', to='category.Category'),
        ),
    ]
